[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = "${{PORT}}"

[[services]]
name = "blkout-community-platform"
source = "."

[services.env]
NEXT_PUBLIC_SUPABASE_URL = "${{NEXT_PUBLIC_SUPABASE_URL}}"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "${{NEXT_PUBLIC_SUPABASE_ANON_KEY}}"
SUPABASE_ANON_KEY = "${{SUPABASE_ANON_KEY}}"
VITE_SUPABASE_URL = "${{VITE_SUPABASE_URL}}"
VITE_SUPABASE_ANON_KEY = "${{VITE_SUPABASE_ANON_KEY}}"