/**
 * Automation Tab Component
 * Quick actions for campaign automation workflows
 */

import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  FileText,
  Calendar,
  Palette,
  Download,
  Table,
  Users,
  FileOutput,
  Play,
  CheckCircle,
  XCircle,
  Clock,
  Loader2,
  History,
  AlertCircle
} from 'lucide-react';
import type { Campaign, QuickAction } from '../types';
import { useScheduleEvents, usePipelineHealth } from '../hooks/useCampaigns';
import { getCampaignSummary } from '../services/campaignLoader';

interface AutomationTabProps {
  campaigns: Campaign[];
}

interface ActionLog {
  id: string;
  actionName: string;
  status: 'success' | 'error' | 'info';
  timestamp: Date;
  message: string;
  details?: string[];
}

interface ActionState {
  [key: string]: boolean;
}

// Utility: Trigger file download
const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Utility: Format date for ICS (YYYYMMDDTHHMMSSZ)
const formatICSDate = (date: Date): string => {
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
};

// Utility: Format date for display
const formatDisplayDate = (date: Date): string => {
  return date.toLocaleDateString('en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

export const AutomationTab: React.FC<AutomationTabProps> = ({ campaigns }) => {
  const [loadingStates, setLoadingStates] = useState<ActionState>({});
  const [actionLogs, setActionLogs] = useState<ActionLog[]>([]);

  // Get schedule events and pipeline health
  const scheduleEvents = useScheduleEvents(campaigns);
  const { checks: pipelineChecks, overallStatus } = usePipelineHealth(campaigns);

  // Add action to log
  const addLog = useCallback((
    actionName: string,
    status: 'success' | 'error' | 'info',
    message: string,
    details?: string[]
  ) => {
    const newLog: ActionLog = {
      id: `${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
      actionName,
      status,
      timestamp: new Date(),
      message,
      details
    };
    setActionLogs(prev => [newLog, ...prev].slice(0, 10));
  }, []);

  // Set loading state helper
  const setLoading = useCallback((actionId: string, isLoading: boolean) => {
    setLoadingStates(prev => ({ ...prev, [actionId]: isLoading }));
  }, []);

  // Action: Generate Newsletter Brief
  const generateNewsletterBrief = useCallback(async () => {
    setLoading('newsletter-brief', true);
    try {
      const newsletterItems = campaigns.flatMap(c =>
        c.contentItems.filter(item => item.type === 'newsletter')
      );

      if (newsletterItems.length === 0) {
        addLog('Generate Newsletter Brief', 'error', 'No newsletter content found in campaigns');
        return;
      }

      const markdown = `# BLKOUT Newsletter Brief
Generated: ${formatDisplayDate(new Date())}

## Campaigns Included
${campaigns.map(c => `- **${c.name}** (${c.status})`).join('\n')}

---

${campaigns.map(campaign => {
  const items = campaign.contentItems.filter(i => i.type === 'newsletter');
  if (items.length === 0) return '';

  return `## ${campaign.name}
**Tagline:** ${campaign.tagline}
**Campaign Voice:** ${campaign.voice || 'Not specified'}
**Launch Date:** ${formatDisplayDate(campaign.launchDate)}

### Newsletter Content
${items.map(item => `
#### ${item.title}
- **Status:** ${item.status}
- **Platform:** ${item.platform}
${item.scheduledFor ? `- **Scheduled:** ${formatDisplayDate(item.scheduledFor)}` : ''}
${item.content ? `\n**Content:**\n${item.content}` : ''}
`).join('\n')}

---
`;
}).join('\n')}

## Key Messages
${campaigns.map(c => `- ${c.tagline}`).join('\n')}

## Visual Assets Needed
${campaigns.flatMap(c =>
  c.contentItems.filter(i => i.type === 'graphic' && i.status === 'idea')
    .map(i => `- [ ] ${i.title}`)
).join('\n') || '- No pending visual assets'}

---
*Generated by BLKOUT Campaign Dashboard*
`;

      downloadFile(markdown, `newsletter-brief-${new Date().toISOString().split('T')[0]}.md`, 'text/markdown');
      addLog('Generate Newsletter Brief', 'success', `Downloaded brief with ${newsletterItems.length} newsletter items`);
    } catch (error) {
      addLog('Generate Newsletter Brief', 'error', `Failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading('newsletter-brief', false);
    }
  }, [campaigns, addLog, setLoading]);

  // Action: Export Calendar (.ics)
  const exportCalendar = useCallback(async () => {
    setLoading('export-calendar', true);
    try {
      if (scheduleEvents.length === 0) {
        addLog('Export Calendar', 'error', 'No scheduled events found in campaigns');
        return;
      }

      const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//BLKOUT//Campaign Calendar//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:BLKOUT Campaign Schedule
X-WR-TIMEZONE:Europe/London
${scheduleEvents.map(event => {
  const campaign = campaigns.find(c => c.id === event.campaignId);
  const endTime = event.end || new Date(event.start.getTime() + 60 * 60 * 1000); // Default 1 hour duration
  return `BEGIN:VEVENT
UID:${event.id}@blkout.community
DTSTAMP:${formatICSDate(new Date())}
DTSTART:${formatICSDate(event.start)}
DTEND:${formatICSDate(endTime)}
SUMMARY:${event.title}
DESCRIPTION:Campaign: ${campaign?.name || 'Unknown'}\\nPlatform: ${event.platform}\\nStatus: ${event.status}
CATEGORIES:${event.platform.toUpperCase()},BLKOUT
STATUS:${event.status === 'published' ? 'COMPLETED' : 'CONFIRMED'}
END:VEVENT`;
}).join('\n')}
END:VCALENDAR`;

      downloadFile(icsContent, `blkout-campaign-calendar-${new Date().toISOString().split('T')[0]}.ics`, 'text/calendar');
      addLog('Export Calendar', 'success', `Downloaded calendar with ${scheduleEvents.length} events`);
    } catch (error) {
      addLog('Export Calendar', 'error', `Failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading('export-calendar', false);
    }
  }, [scheduleEvents, campaigns, addLog, setLoading]);

  // Action: Create Canva Brief
  const createCanvaBrief = useCallback(async () => {
    setLoading('canva-brief', true);
    try {
      const visualAssets = campaigns.flatMap(c =>
        c.contentItems.filter(item => item.type === 'graphic' || item.type === 'video')
      );

      const markdown = `# BLKOUT Design Brief for Canva
Generated: ${formatDisplayDate(new Date())}

## Brand Guidelines
- **Primary Colors:** Purple (#7C3AED), Black (#000000), White (#FFFFFF)
- **Accent Colors:** Pink (#EC4899), Gold (#F59E0B)
- **Typography:** Bold, modern, accessible
- **Style:** Vibrant, community-focused, celebratory

---

${campaigns.map(campaign => {
  const assets = campaign.contentItems.filter(i => i.type === 'graphic' || i.type === 'video');
  const socialPosts = campaign.contentItems.filter(i => i.type === 'social');

  return `## Campaign: ${campaign.name}
**Tagline:** ${campaign.tagline}
**Campaign Period:** ${formatDisplayDate(campaign.launchDate)} - ${formatDisplayDate(campaign.endDate)}
**Voice:** ${campaign.voice || 'Empowering, Community-focused'}

### Visual Assets Needed (${assets.length})
${assets.map(asset => `
#### ${asset.title}
- **Type:** ${asset.type}
- **Platform:** ${asset.platform}
- **Status:** ${asset.status}
- **Dimensions:** ${asset.platform === 'instagram' ? '1080x1080 (feed), 1080x1920 (story)' :
  asset.platform === 'twitter' ? '1200x675' :
  asset.platform === 'linkedin' ? '1200x627' : 'As needed'}
${asset.content ? `- **Content Direction:** ${asset.content.substring(0, 200)}...` : ''}
`).join('\n')}

### Social Post Graphics (${socialPosts.length})
${socialPosts.slice(0, 5).map(post => `
- **${post.title}** (${post.platform})
  - Status: ${post.status}
  - ${post.scheduledFor ? `Scheduled: ${formatDisplayDate(post.scheduledFor)}` : 'Not scheduled'}
`).join('')}
${socialPosts.length > 5 ? `\n*...and ${socialPosts.length - 5} more posts*\n` : ''}

---
`;
}).join('\n')}

## Design Checklist
${visualAssets.map(asset => `- [ ] ${asset.title} (${asset.platform})`).join('\n') || '- No visual assets defined'}

## Key Dates
${campaigns.map(c => `- **${c.name} Launch:** ${formatDisplayDate(c.launchDate)}`).join('\n')}

---
*Generated by BLKOUT Campaign Dashboard*
*Import to Canva and use BLKOUT brand kit*
`;

      downloadFile(markdown, `canva-design-brief-${new Date().toISOString().split('T')[0]}.md`, 'text/markdown');
      addLog('Create Canva Brief', 'success', `Downloaded design brief with ${visualAssets.length} assets`);
    } catch (error) {
      addLog('Create Canva Brief', 'error', `Failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading('canva-brief', false);
    }
  }, [campaigns, addLog, setLoading]);

  // Action: Generate Status Report
  const generateStatusReport = useCallback(async () => {
    setLoading('status-report', true);
    try {
      const summaries = campaigns.map(c => ({ campaign: c, summary: getCampaignSummary(c) }));

      const statusIcon = (status: string) => {
        switch (status) {
          case 'passing': return '[PASS]';
          case 'warning': return '[WARN]';
          case 'failing': return '[FAIL]';
          default: return '[----]';
        }
      };

      const markdown = `# BLKOUT Campaign Status Report
Generated: ${formatDisplayDate(new Date())}

## Executive Summary
- **Total Campaigns:** ${campaigns.length}
- **Active Campaigns:** ${campaigns.filter(c => c.status === 'active').length}
- **Overall Pipeline Health:** ${overallStatus.toUpperCase()}
- **Total Content Items:** ${summaries.reduce((sum, s) => sum + s.summary.totalItems, 0)}
- **Completed Items:** ${summaries.reduce((sum, s) => sum + s.summary.completedItems, 0)}

---

${summaries.map(({ campaign, summary }) => `## ${campaign.name}
**Status:** ${campaign.status.toUpperCase()}
**Tagline:** ${campaign.tagline}
**Period:** ${formatDisplayDate(campaign.launchDate)} - ${formatDisplayDate(campaign.endDate)}
**Days Remaining:** ${summary.daysRemaining}

### Content Progress
- **Completion:** ${summary.completionPercentage}% (${summary.completedItems}/${summary.totalItems} items)
- **By Status:**
${Object.entries(summary.contentByStatus).map(([status, count]) =>
  `  - ${status}: ${count}`
).join('\n')}
- **By Platform:**
${Object.entries(summary.contentByPlatform).map(([platform, count]) =>
  `  - ${platform}: ${count}`
).join('\n')}

### Agent Tasks (${campaign.agentTasks.length})
${campaign.agentTasks.length > 0 ?
  campaign.agentTasks.map(task =>
    `- [${task.status.toUpperCase()}] **${task.agentId}** (${task.priority}): ${task.description.substring(0, 100)}${task.description.length > 100 ? '...' : ''}`
  ).join('\n')
  : '- No agent tasks defined'}

### Metrics
${campaign.metrics.targetReach ? `- **Target Reach:** ${campaign.metrics.targetReach.toLocaleString()}` : ''}
${campaign.metrics.applications ? `- **Applications:** ${campaign.metrics.applications.current || 0}/${campaign.metrics.applications.target} target` : ''}
${campaign.metrics.registrations ? `- **Registrations:** ${campaign.metrics.registrations.current || 0}/${campaign.metrics.registrations.target} target` : ''}

---
`).join('\n')}

## Pipeline Health Checks
${pipelineChecks.map(check => `${statusIcon(check.status)} **${check.name}** - ${check.description}${check.details ? ` (${check.details})` : ''}`).join('\n')}

## Scheduled Events (Next 30 Days)
${scheduleEvents
  .filter(e => e.start <= new Date(Date.now() + 30 * 24 * 60 * 60 * 1000))
  .sort((a, b) => a.start.getTime() - b.start.getTime())
  .slice(0, 20)
  .map(e => `- ${formatDisplayDate(e.start)} - **${e.title}** (${e.platform})`)
  .join('\n') || '- No events scheduled in the next 30 days'}

## Action Items
${pipelineChecks.filter(c => c.status === 'failing' || c.status === 'warning').map(check =>
  `- [ ] Fix: ${check.name} - ${check.description}`
).join('\n') || '- All pipeline checks passing!'}

---
*Generated by BLKOUT Campaign Dashboard*
`;

      downloadFile(markdown, `campaign-status-report-${new Date().toISOString().split('T')[0]}.md`, 'text/markdown');
      addLog('Generate Status Report', 'success', `Downloaded report for ${campaigns.length} campaigns`);
    } catch (error) {
      addLog('Generate Status Report', 'error', `Failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading('status-report', false);
    }
  }, [campaigns, pipelineChecks, scheduleEvents, overallStatus, addLog, setLoading]);

  // Action: Sync to Sheets
  const syncToSheets = useCallback(async () => {
    setLoading('sync-sheets', true);
    try {
      // Check if Google Sheets integration is configured
      const sheetsApiKey = import.meta.env.VITE_GOOGLE_SHEETS_API_KEY;
      const sheetsSpreadsheetId = import.meta.env.VITE_GOOGLE_SHEETS_SPREADSHEET_ID;

      if (!sheetsApiKey || !sheetsSpreadsheetId) {
        addLog('Sync to Sheets', 'info', 'Google Sheets integration not configured', [
          'To enable this feature, add to your .env:',
          'VITE_GOOGLE_SHEETS_API_KEY=your_api_key',
          'VITE_GOOGLE_SHEETS_SPREADSHEET_ID=your_spreadsheet_id',
          '',
          'Create a service account at console.cloud.google.com',
          'Enable Google Sheets API',
          'Share your spreadsheet with the service account email'
        ]);
        return;
      }

      // If configured, attempt sync (placeholder for actual implementation)
      addLog('Sync to Sheets', 'info', 'Google Sheets sync ready but API implementation pending', [
        `Spreadsheet ID: ${sheetsSpreadsheetId.substring(0, 10)}...`,
        `Campaigns to sync: ${campaigns.length}`,
        `Total content items: ${campaigns.reduce((sum, c) => sum + c.contentItems.length, 0)}`
      ]);
    } catch (error) {
      addLog('Sync to Sheets', 'error', `Failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading('sync-sheets', false);
    }
  }, [campaigns, addLog, setLoading]);

  // Action: Run All Agents
  const runAllAgents = useCallback(async () => {
    setLoading('run-agents', true);
    try {
      const allAgentTasks = campaigns.flatMap(c =>
        c.agentTasks.map(task => ({
          ...task,
          campaignName: c.name,
          campaignId: c.id
        }))
      );

      if (allAgentTasks.length === 0) {
        addLog('Run All Agents', 'info', 'No agent tasks defined in campaigns', [
          'Add agent_tasks to your campaign JSON files:',
          '  "agent_tasks": {',
          '    "content_writer": {',
          '      "task_id": "write-posts",',
          '      "prompt": "Write social media posts",',
          '      "priority": "high"',
          '    }',
          '  }'
        ]);
        return;
      }

      const tasksByPriority = {
        high: allAgentTasks.filter(t => t.priority === 'high'),
        medium: allAgentTasks.filter(t => t.priority === 'medium'),
        low: allAgentTasks.filter(t => t.priority === 'low')
      };

      const details = [
        `Total agent tasks: ${allAgentTasks.length}`,
        `High priority: ${tasksByPriority.high.length}`,
        `Medium priority: ${tasksByPriority.medium.length}`,
        `Low priority: ${tasksByPriority.low.length}`,
        '',
        '--- Agent Task Queue ---',
        ...allAgentTasks.map(task =>
          `[${task.priority.toUpperCase()}] ${task.agentId} (${task.campaignName}): ${task.description.substring(0, 60)}${task.description.length > 60 ? '...' : ''}`
        )
      ];

      addLog('Run All Agents', 'info', `${allAgentTasks.length} agent tasks ready to execute`, details);
    } catch (error) {
      addLog('Run All Agents', 'error', `Failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    } finally {
      setLoading('run-agents', false);
    }
  }, [campaigns, addLog, setLoading]);

  // Define quick actions
  const quickActions: QuickAction[] = [
    {
      id: 'newsletter-brief',
      name: 'Generate Newsletter Brief',
      description: 'Create a draft newsletter brief from campaign content',
      icon: 'FileText',
      handler: generateNewsletterBrief
    },
    {
      id: 'export-calendar',
      name: 'Export Calendar (.ics)',
      description: 'Download campaign schedule as calendar file',
      icon: 'Download',
      handler: exportCalendar
    },
    {
      id: 'canva-brief',
      name: 'Create Canva Brief',
      description: 'Generate design brief for Canva templates',
      icon: 'Palette',
      handler: createCanvaBrief
    },
    {
      id: 'status-report',
      name: 'Generate Status Report',
      description: 'Create comprehensive campaign status report',
      icon: 'FileOutput',
      handler: generateStatusReport
    },
    {
      id: 'sync-sheets',
      name: 'Sync to Sheets',
      description: 'Update Google Sheets with campaign data',
      icon: 'Table',
      handler: syncToSheets
    },
    {
      id: 'run-agents',
      name: 'Run All Agents',
      description: 'Execute all automation agents for campaigns',
      icon: 'Users',
      handler: runAllAgents
    }
  ];

  // Icon mapping
  const getIcon = (iconName: string) => {
    const icons: Record<string, React.ComponentType<{ className?: string }>> = {
      FileText,
      Calendar,
      Palette,
      Download,
      Table,
      Users,
      FileOutput
    };
    return icons[iconName] || FileText;
  };

  // Format relative time
  const formatRelativeTime = (date: Date): string => {
    const seconds = Math.floor((Date.now() - date.getTime()) / 1000);
    if (seconds < 60) return 'just now';
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    return `${hours}h ago`;
  };

  return (
    <motion.div
      key="automation"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="space-y-8"
    >
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">
          Quick Actions
        </h2>
        <p className="text-gray-600 dark:text-gray-400 mt-1">
          Run automation workflows for {campaigns.length} campaign{campaigns.length !== 1 ? 's' : ''}
        </p>
      </div>

      {/* Actions Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <AnimatePresence>
          {quickActions.map((action, index) => {
            const Icon = getIcon(action.icon);
            const isLoading = loadingStates[action.id];

            return (
              <motion.div
                key={action.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.05 }}
                whileHover={{ scale: isLoading ? 1 : 1.02 }}
                className={`
                  bg-white dark:bg-gray-800 rounded-xl border-2
                  ${isLoading
                    ? 'border-purple-300 dark:border-purple-700'
                    : 'border-gray-200 dark:border-gray-700 hover:border-purple-400 dark:hover:border-purple-500'
                  }
                  p-6 transition-all duration-200
                `}
              >
                {/* Icon */}
                <div className={`
                  w-14 h-14 rounded-xl flex items-center justify-center mb-4
                  ${isLoading
                    ? 'bg-purple-100 dark:bg-purple-900/30'
                    : 'bg-gray-100 dark:bg-gray-700'
                  }
                `}>
                  {isLoading ? (
                    <Loader2 className="w-7 h-7 text-purple-600 animate-spin" />
                  ) : (
                    <Icon className="w-7 h-7 text-gray-600 dark:text-gray-300" />
                  )}
                </div>

                {/* Content */}
                <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
                  {action.name}
                </h3>
                <p className="text-sm text-gray-600 dark:text-gray-400 mb-4 min-h-[40px]">
                  {action.description}
                </p>

                {/* Run Button */}
                <button
                  onClick={action.handler}
                  disabled={isLoading || action.disabled}
                  className={`
                    w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg
                    font-medium transition-colors
                    ${isLoading
                      ? 'bg-purple-100 dark:bg-purple-900/30 text-purple-600 cursor-wait'
                      : 'bg-purple-600 hover:bg-purple-700 text-white'
                    }
                    disabled:opacity-50 disabled:cursor-not-allowed
                  `}
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Running...
                    </>
                  ) : (
                    <>
                      <Play className="w-4 h-4" />
                      Run
                    </>
                  )}
                </button>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>

      {/* Recent Actions Log */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3 }}
        className="bg-white dark:bg-gray-800 rounded-xl border-2 border-gray-200 dark:border-gray-700 p-6"
      >
        <div className="flex items-center gap-3 mb-4">
          <History className="w-5 h-5 text-gray-600 dark:text-gray-400" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            Recent Actions
          </h3>
        </div>

        {actionLogs.length === 0 ? (
          <div className="text-center py-8 text-gray-500 dark:text-gray-400">
            <Clock className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p>No actions run yet</p>
            <p className="text-sm">Run an action above to see it logged here</p>
          </div>
        ) : (
          <div className="space-y-3">
            <AnimatePresence>
              {actionLogs.map((log) => {
                const statusColors = {
                  success: {
                    bg: 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800',
                    text: 'text-green-800 dark:text-green-200',
                    subtext: 'text-green-600 dark:text-green-400',
                    icon: <CheckCircle className="w-5 h-5 text-green-600 dark:text-green-400 flex-shrink-0" />
                  },
                  error: {
                    bg: 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800',
                    text: 'text-red-800 dark:text-red-200',
                    subtext: 'text-red-600 dark:text-red-400',
                    icon: <XCircle className="w-5 h-5 text-red-600 dark:text-red-400 flex-shrink-0" />
                  },
                  info: {
                    bg: 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800',
                    text: 'text-blue-800 dark:text-blue-200',
                    subtext: 'text-blue-600 dark:text-blue-400',
                    icon: <AlertCircle className="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0" />
                  }
                };
                const colors = statusColors[log.status];

                return (
                  <motion.div
                    key={log.id}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    className={`p-3 rounded-lg border ${colors.bg}`}
                  >
                    <div className="flex items-start gap-4">
                      {colors.icon}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <p className={`font-medium ${colors.text}`}>
                            {log.actionName}
                          </p>
                          <span className="text-xs text-gray-500 dark:text-gray-400 flex-shrink-0">
                            {formatRelativeTime(log.timestamp)}
                          </span>
                        </div>
                        <p className={`text-sm ${colors.subtext}`}>
                          {log.message}
                        </p>
                        {log.details && log.details.length > 0 && (
                          <details className="mt-2">
                            <summary className={`text-xs cursor-pointer ${colors.subtext} hover:underline`}>
                              Show details ({log.details.length} lines)
                            </summary>
                            <pre className={`mt-2 text-xs p-2 rounded bg-black/5 dark:bg-white/5 ${colors.subtext} overflow-x-auto max-h-40 overflow-y-auto`}>
                              {log.details.join('\n')}
                            </pre>
                          </details>
                        )}
                      </div>
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
        )}
      </motion.div>
    </motion.div>
  );
};

export default AutomationTab;
