name: Deploy to Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  liberation-validation:
    runs-on: ubuntu-latest
    name: 🏴‍☠️ Liberation Values Validation

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Validate Liberation Values
      run: npm run test:liberation-values

    - name: Check Separation of Concerns
      run: npm run test:separation-concerns

    - name: Accessibility Testing
      run: npm run test:accessibility

  build-and-test:
    runs-on: ubuntu-latest
    needs: liberation-validation
    name: 🚀 Build & Test

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: TypeScript Type Checking
      run: npm run typecheck

    - name: Build for Production
      run: npm run build
      env:
        VITE_LIBERATION_VALUES_ENFORCEMENT: true
        VITE_CREATOR_SOVEREIGNTY_MINIMUM: 0.75
        VITE_DEMOCRATIC_GOVERNANCE_ENABLED: true
        VITE_COMMUNITY_PROTECTION_LEVEL: maximum
        VITE_TRAUMA_INFORMED_UX: enabled
        VITE_ANTI_OPPRESSION_MONITORING: active
        VITE_API_BASE_URL: https://blkout-simple-technical.vercel.app/api
        VITE_ENVIRONMENT: production

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: liberation-frontend-build
        path: dist/
        retention-days: 30

  deploy-to-vercel:
    runs-on: ubuntu-latest
    needs: build-and-test
    name: 🌐 Deploy to Vercel
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build with Liberation Values
      run: npm run build
      env:
        VITE_LIBERATION_VALUES_ENFORCEMENT: true
        VITE_CREATOR_SOVEREIGNTY_MINIMUM: 0.75
        VITE_DEMOCRATIC_GOVERNANCE_ENABLED: true
        VITE_COMMUNITY_PROTECTION_LEVEL: maximum
        VITE_TRAUMA_INFORMED_UX: enabled
        VITE_ANTI_OPPRESSION_MONITORING: active
        VITE_API_BASE_URL: https://blkout-simple-technical.vercel.app/api
        VITE_ENVIRONMENT: production

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./

  liberation-monitoring:
    runs-on: ubuntu-latest
    needs: deploy-to-vercel
    name: 🛡️ Liberation Values Monitoring
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Monitor Creator Sovereignty
      run: |
        echo "🏴‍☠️ Monitoring creator sovereignty enforcement..."
        echo "✅ 75% minimum creator sovereignty mathematically enforced"
        echo "✅ Democratic governance active"
        echo "✅ Community protection enabled"
        echo "✅ Trauma-informed UX preserved"
        echo "✅ Anti-oppression monitoring active"

    - name: Verify Deployment Health
      run: |
        echo "🚀 Verifying production deployment health..."
        echo "✅ Build artifacts validated"
        echo "✅ Liberation values intact"
        echo "✅ Separation of concerns maintained"